<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <TargetFrameworks Condition=" '$(OS)' == 'Windows_NT' ">$(TargetFrameworks);net462</TargetFrameworks>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <PropertyGroup>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Optimize>true</Optimize>
    <Configuration>Release</Configuration>
    <IsPackable>false</IsPackable>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="Microsoft.VisualStudio.DiagnosticsHub.BenchmarkDotNetDiagnosers" Version="18.7.37220.1" Condition=" '$(TargetFramework)' != 'net462' " />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\ExcelDataReader\ExcelDataReader.csproj" />
    <Compile Include="..\ExcelDataReader.Tests\AllocationTestWorkbook.cs" Link="AllocationTestWorkbook.cs" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net462'">
    <Reference Include="System.IO.Compression" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\TestData\10x10000.xlsx" />
    <EmbeddedResource Include="..\TestData\10x10000.xlsb" />
    <EmbeddedResource Include="..\TestData\10x10000.xls" />
    <EmbeddedResource Include="..\TestData\Issue289.xlsx" />
    <EmbeddedResource Include="..\TestData\BigFormatted.xls" />
    <EmbeddedResource Include="..\TestData\BigFormatted.xlsx" />
    <EmbeddedResource Include="..\TestData\Issue263.xls" />
    <EmbeddedResource Include="..\TestData\OldIssue11572_CodePage.xls" />
    <EmbeddedResource Include="..\TestData\Issue173.xls" />
    <EmbeddedResource Include="..\TestData\InvalidByteOrderValueInHeader.xls" />
    <EmbeddedResource Include="..\TestData\LotsOfSheets.xls" />
    <EmbeddedResource Include="..\TestData\LotsOfSheets.xlsx" />
    <EmbeddedResource Include="..\TestData\LotsOfSheets.xlsb" />
    <EmbeddedResource Include="..\TestData\agile_AES128_SHA1_CBC_pwd_password.xlsx" />
    <EmbeddedResource Include="..\TestData\standard_AES128_SHA1_ECB_pwd_password.xlsx" />
    <EmbeddedResource Include="..\TestData\Issue242_StdRc4PwdPassword.xls" />
    <EmbeddedResource Include="..\TestData\Issue242_XorPwdPassword.xls" />
  </ItemGroup>
</Project>