name: CI

on:
  push:
    branches: ['**']
    tags-ignore: ['**']
  pull_request:

permissions: {}

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore
        run: dotnet restore --locked-mode

      - name: Build
        run: dotnet build ExcelDataReader.sln --no-restore -c Release /p:TreatWarningsAsErrors=true

      - name: Test
        run: dotnet test src/ExcelDataReader.Tests/ExcelDataReader.Tests.csproj --no-build -c Release
